import { Metadata } from 'next';

export const SITE_CONFIG: Metadata = {
    title: {
        default: 'WahabArf || Personal Portfolio',
        template: `%s | NextJs`,
    },

    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: './public/favicon.ico',
                href: './public/favicon/ico',
            },
        ],
    },
    openGraph: {
        title: 'WahabArf || Personal Portfolio',
        description: 'Personal Website by NextJs',
    },
    twitter: {
        card: 'summary_large_image',
        creator: '@WahabArf',
        title: 'WahabArf || Personal Portfolio',
        description: 'Personal Website by NextJs',
    },
    metadataBase: new URL('https://next-js-chi-green.vercel.app/'),
};
